### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by pablomp** [geojson-xyz/geojson-xyz#11]
I get a 'Missing Cross-Origin Resource Sharing (CORS) Response Header' when trying to include a .geojson via LeafLet & Ajax

**Comment by tmcw** [comment]
This is fixed on the source side, going to roll an update of geojson-xyz that points to the new URLs.

**Comment by tmcw** [comment]
Fixed in 82c558ca91236c10618c833bbe463006f045736a
