### ISSUE TITLE
Down arrows not working on Windows

### ISSUE THREAD

**Issue by mtravis** [geojson-xyz/geojson-xyz#8]
Down arrows don't appear to work on the first selection list so I can only select water.

All subsequent lists work fine and I can download the data. 

Really cool idea by the way!

**Comment by tmcw** [comment]
This would likely be an upstream issue in [Inquirer.js](https://github.com/SBoudrias/Inquirer.js/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+windows), the module that powers geojson-xyz's cli menu selection interface.

**Comment by mtravis** [comment]
Ok, I'll raise it there thanks.

**Comment by tmcw** [comment]
upstream

https://github.com/SBoudrias/Inquirer.js/issues/266

upstream of that

https://github.com/nodejs/node/issues/5384

**Comment by tmcw** [comment]
Fixed in node v5.3.0 according to 2nd-level upstream ticket.
