### ISSUE TITLE
Include features' name property in fuzzy match

### ISSUE THREAD

**Issue by anandthakker** [geojson-xyz/geojson-xyz#9]
I've long wished I could do something like `geojson-xyz maryland -- | geojsonio`. 

Seems like this would be quite doable here by indexing the `name` property of each feature of each file.  Sure, `name` is partly arbitrary and there would be lots of duplicates, but I think it would be hella useful much of the time nonetheless

**Comment by anandthakker** [comment]
^ @tmcw if you're into it I'd be up for working on a PR along those lines this weekend

**Comment by tmcw** [comment]
:+1: would be interested in whether the tabular (properties property) part of the data is small enough, or if we could use a subset of rows/columns to do so. This would make really good metadata.

**Comment by anandthakker** [comment]
Just a dumb dump of the properties as CSV is ~ 26M
